language: dart

services:
  - docker

before_install:
  - docker build -t=ci .

script:
  - docker container run -v $(pwd)/build:/usr/src/myapp/coverage ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
