name: dart_style_rin
description: A formatter for Dart code to show object composition.
version: 0.1.0
homepage: https://github.com/levelrin/DartStyleRin
issue_tracker: https://github.com/levelrin/DartStyleRin/issues
author: Rin <levelrin@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.2
  meta: ^1.1.8
  quiver: ^2.1.3

dev_dependencies:
  test: ^1.6.0
  test_coverage: ^0.4.0
